sudo: false

language: go

go:
  - "1.11.x"
  - tip

env:
  GO111MODULE=on

git:
  depth: 1

matrix:
  allow_failures:
  - go: tip
  fast_finish: true

install:
- go get -mod=readonly -v ./...
- go get -u github.com/client9/misspell/cmd/misspell
- go get -u honnef.co/go/tools/cmd/staticcheck


before_script:
- go vet
- go mod verify
- misspell -error -locale US *.go
- staticcheck
- ./.travis.gofmt.sh

script: make test

notifications:
  slack:
    secure: m8ec8U2CqPqLQPvFuvIjkI2n82mFVzJ2c/xkfV5gDrc5ujiZNKaw3GHbPbjc9Mr2b8z5vCRGKTKRNO4zGuognoOckvyAAHfxS4lpPcpwOWrSEZN4TGKW4tpCr453VaxLT34Pcjfi5pPxamHcYOzgl7SWrAv1aGgDZ5QWeVlQU7pB14nxJnWFc9FW3B6FKcXxiDOEbjCDFHSHl7xcs0E8qb7rSCYD2nTncXPTwfA2dqoij72VjwIVrddxwMgA+jJvnb0ScP3Z3G0oz6TZCZLVzxw6V6EMQf54SLVsfWe74xAUcbaUeWk5sijXt4yLeQheZcJpgOXqRQ0LIZWhNcAqYNqIlFesTtlVbN45L2xW10a308PV8ZrX/Svm09CYIliZuwC10HO49x7lGswL1eBIM2ZxYEmTXg6/EHOBm0MLirKUwwkj9O8R4tsE0te1IcTmZLZ4Doh++xKQhdRMlrcALEZ4zR5J8zAGW2VxFsKYZ6pNPqiA9aBB/6WE1fl7vaUPsIIbV82186apLWAdX78BIMcTJEi7erK8Vqqx6yNnxl9gZlYNU4MKd4Kd7SHqHsoeZgUIPy/ctLIDb1rs639tMcIy6RBc01KN4l+ZwdwAsunD8rHxVPF8mZVJ/O46Tf8vrOziA6EdpT676TjB6fAj7Q+8JKx+NAcMndRKLcJlsew=
